### ISSUE TITLE
RuntimeError: The size of tensor a (2) must match the size of tensor b (10) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Joanna-0421** [wangren09/TrojanNetDetector#4]
When running the main_dftnd file, the following error occurs, I hope you can help me. Thank you.

RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/kemove/anaconda3/envs/pytorch_1_10/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/kemove/anaconda3/envs/pytorch_1_10/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/workplace/ziyuan/TrojanNetDetector-master/DFTND/robustness_lib/robustness/attacker.py", line 290, in forward
    adv = self.attacker(inp, target, **attacker_kwargs)
  File "/home/kemove/anaconda3/envs/pytorch_1_10/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/workplace/ziyuan/TrojanNetDetector-master/DFTND/robustness_lib/robustness/attacker.py", line 273, in forward
    adv_ret = get_adv_examples(x)
  File "/data/workplace/ziyuan/TrojanNetDetector-master/DFTND/robustness_lib/robustness/attacker.py", line 128, in get_adv_examples
    losses = losses * W1
RuntimeError: The size of tensor a (2) must match the size of tensor b (10) at non-singleton dimension 0

**Comment by wangren09** [comment]
Several causes are possible:

1. You have multiple GPUs and the data live in different GPUs (or it could be some data are not moved to GPU but live in CPU instead).
2. Your input data fed into the attacker are not in the tensor format. You can check the data fed into the attacker.
3. The python version issue. I am pretty sure that this code works fine in Python 3.7, as mentioned in the Platform requirement. But I haven't checked Python 3.8. So try to switch python versions. Here is an instruction on how to switch Python versions https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux

Hope this helps

**Comment by wangren09** [comment]
Several causes are possible:

1. The python version issue. I am pretty sure that this code works fine in Python 3.7, as mentioned in the Platform requirement. But I haven't checked Python 3.8. So try to switch python versions. Here is an instruction on how to switch Python versions https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux
2. Check the dimensions of your data. There seems a dimension mismatch.
3. You have multiple GPUs and the data live in different GPUs (or it could be some data are not moved to GPU but live in CPU instead).
4. Your input data fed into the attacker are not in the tensor format. You can check the data fed into the attacker.

Hope this helps

**Comment by Joanna-0421** [comment]
> Several causes are possible:
> 
> 1. The python version issue. I am pretty sure that this code works fine in Python 3.7, as mentioned in the Platform requirement. But I haven't checked Python 3.8. So try to switch python versions. Here is an instruction on how to switch Python versions https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux
> 2. Check the dimensions of your data. There seems a dimension mismatch.
> 3. You have multiple GPUs and the data live in different GPUs (or it could be some data are not moved to GPU but live in CPU instead).
> 4. Your input data fed into the attacker are not in the tensor format. You can check the data fed into the attacker.
> 
> Hope this helps

Thank you very much for your reply. I think maybe I have multiple GPUs causing the problem.  How should I change the code to fit multiple GPUs.  Thanks again.
